{{- if and .Values.packageFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-red.configMapName" . }}
data:
  package.json:
    {{- toYaml .Values.packageFile | nindent 4 }}
{{- end -}}
